version: '2.1'

volumes:
  pihole_config:
  dnsmasq_config:
  dnscrypt_config:
  settings:

services:
  pihole:
    build: ./pihole
    privileged: true
    volumes:
      - 'pihole_config:/etc/pihole'
      - 'dnsmasq_config:/etc/dnsmasq.d'
    dns:
      - '127.0.0.1'
      - '1.1.1.1'
    network_mode: host

  # set pihole DNS1 and DNS2 service variables to 127.0.0.1#5053 to use dnscrypt-proxy for upstream DNS
  dnscrypt-proxy:
    build: ./dnscrypt-proxy
    volumes:
      - 'dnscrypt_config:/config'
    ports:
      - '5053:5053/udp'


  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/usr/src/app/settings'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  photos:
    privileged: true
    restart: always
    build: ./photos
    ports:
      - "8888:8888"
     