FROM amd.64/python:3.7-stretch
RUN apt update && apt install watch -y
CMD apt-cache --clean
WORKDIR /root

COPY requirements.txt . 
COPY piholestats.sh . 
RUN pip3 install -r requirements.txt


RUN chmod 0744 piholestats.sh 




CMD watch -n 60 python3 piholestats.sh
